version: '3.8'

services:
  ipam-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ipam-app-local:latest
    container_name: ipam_app_local_prod
    ports:
      - "3010:3000"
    env_file:
      - ./production.env
    restart: unless-stopped
    networks:
      - app_network
    volumes:
      - ./next.config.js:/app/next.config.js:ro # For easier modification of allowedOrigins
      - ipam_db_data:/app/prisma # Persist the entire prisma directory (contains dev.db and schema)

networks:
  app_network:
    driver: bridge

volumes:
  ipam_db_data:
    driver: local # Ensures the volume is managed by Docker on the host
